services:
  - type: web
    name: welfare-namhae
    env: python
    runtime: python-3.11.9
    buildCommand: "pip install --upgrade pip setuptools wheel && pip install --no-cache-dir -r requirements.txt"
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 60"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: "1" 